import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,modal }) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <nav>
      <Link href={'/'}>Home</Link>
      <Link href={'/contact'}>Contact</Link>
      <Link href={'/shop'}> Shop </Link>
    </nav>
    {children}
    {modal}
    </body>
    </html>
  );
}
